server:
  port: 3344
  #应用名称
spring:
  application:
    name: cloud-config-center

  # 配置git仓库地址(以下示例是开放的)-(最后不需带/,否则会出现告警：No custom http config found for URL)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Qyl097731/springcloud-config.git
            # 配置仓库路径(仓库下文件目录）
          searchPaths: springcloud-config
  # 配置仓库的分支
      label: master

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
