server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.48.219:8848

#消费者8.要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider
