server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.48.219:8848 # 配置Nacos的地址
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
