server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: '097731'
  cloud:
    zookeeper:
      #此处的IP地址+端口号2181，为Linux的Zookeeper服务器所在地址
      connect-string: 8.130.48.219:2181


mybatis:
  type-aliases-package: com.njxzc.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

