server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh           #路由的ID，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getPayment/**     #断言，路径相匹配的进行路由
            - After=2022-06-28T21:59:47.279+08:00[Asia/Shanghai]

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb
            - Cookie=username,qyl
            - Header-X-Request-Id,\d+

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true #是否从 EurekaServer 抓取自己有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true #显示IP
    hostname: cloud-gateway-service
